services:
  discord-bytbot:
    build: .
    container_name: discord-bytbot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6666:3000"
    volumes:
      - /home/byttorrent/docker/bytbot:/app/data
